# -*- coding: utf-8 -*-
"""wids_attempt_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zy7DjNwYlUOftGQZK6fhuuDIjgYNMF3s
"""

import numpy as np
import pandas as pd

combined_df = pd.read_csv("COMBINED_DATA.csv")
solutions_df = pd.read_excel("TRAINING_SOLUTIONS.xlsx", sheet_name="training_combined")

# Merge on 'participant_id'
df = combined_df.merge(solutions_df, on="participant_id", how="inner")

# Display the first few rows
print(df.head())

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
from imblearn.over_sampling import SMOTE

# Drop 'participant_id'
df = df.drop(columns=['participant_id'])

# Separate features (X) and targets (y)
X = df.drop(columns=['ADHD_Outcome', 'Sex_F'])
y_adhd = df['ADHD_Outcome']
y_sex = df['Sex_F']

# Handle missing values using KNNImputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5)
X_imputed = imputer.fit_transform(X)

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imputed)

# Apply PCA for feature reduction (retain 95% variance)
pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X_scaled)

### **Separate Training for Each Target Variable**
# 1. ADHD Classification
X_train_adhd, X_test_adhd, y_train_adhd, y_test_adhd = train_test_split(X_pca, y_adhd, test_size=0.2, random_state=42)

# Apply SMOTE to balance classes
smote = SMOTE(random_state=42)
X_train_adhd, y_train_adhd = smote.fit_resample(X_train_adhd, y_train_adhd)

# Train ADHD model
rf_adhd = RandomForestClassifier(n_estimators=200, max_depth=20, random_state=42)
rf_adhd.fit(X_train_adhd, y_train_adhd)
adhd_preds = rf_adhd.predict(X_test_adhd)
adhd_accuracy = accuracy_score(y_test_adhd, adhd_preds)
print(f"ADHD Prediction Accuracy: {adhd_accuracy:.4f}")

# 2. Sex Classification
X_train_sex, X_test_sex, y_train_sex, y_test_sex = train_test_split(X_pca, y_sex, test_size=0.2, random_state=42)

# Apply SMOTE to balance classes
X_train_sex, y_train_sex = smote.fit_resample(X_train_sex, y_train_sex)

# Train Sex model
rf_sex = RandomForestClassifier(n_estimators=200, max_depth=20, random_state=42)
rf_sex.fit(X_train_sex, y_train_sex)
sex_preds = rf_sex.predict(X_test_sex)
sex_accuracy = accuracy_score(y_test_sex, sex_preds)
print(f"Sex Prediction Accuracy: {sex_accuracy:.4f}")

